### ISSUE TITLE
Translate site rendering with odd urls

### ISSUE THREAD

**Issue by KorvinSzanto** [concrete5/translate.concrete5.org#13]
If I go to download a translation from https://translate.concrete5.org/translate/package/concrete5, the rendered urls look wrong:

`https://translate.concrete5.org/ccm/system/block/action/edit/166/Main/51/download_translations_file/53/en_GB/mo?ccm_token=...`

Is this the right url? If so clicking through seems to trigger some `die('Access Denied')` somewhere.

**Comment by mlocati** [comment]
This issue should be fixed by https://github.com/concrete5/concrete5/pull/7036

**Comment by mlocati** [comment]
Fixed
